/**
 * Copyright (c) 2025 Massimo Costantini.
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE file in the project root for full license information.
 */

/**
 * Runtime support for executing jRPL programs.
 *
 * <p>Provides the stack abstraction used by generated bytecode and interpreters,
 * encoding booleans as {@code 1.0} (true) and {@code 0.0} (false).</p>
 *
 * @see org.jrpl.runtime.ExecStack
 */
package org.jrpl.runtime;
